project_id = "lckjlefupqlblfcwhbom"

[functions.track]
verify_jwt = false

[functions.delete-account]
verify_jwt = true

[functions.public-api]
verify_jwt = false

[functions.slack-notify]
verify_jwt = true

[functions.send-email-report]
verify_jwt = false

[functions.sso-saml]
verify_jwt = false

[functions.overlay-stats]
verify_jwt = false
